services:
  vehicle-service:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4000
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/index.js
      "
