services:
  vehicle-service:
    image: exagonsoft/vehicle-service:latest
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://default:lbx7wrmQ8HYd@ep-dark-cake-a4igc6ta-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require&pgbouncer=true&connect_timeout=15"
      PORT: 4000
    command: >
      sh -c "
        sudo apt-get update -y &&
        sudo apt-get install -y openssl &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        node dist/index.js
      "
